# permissions for end users to edit deploywebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployweb-editor-role
rules:
- apiGroups:
  - web.czy.io
  resources:
  - deploywebs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.czy.io
  resources:
  - deploywebs/status
  verbs:
  - get
