# permissions for end users to view deploywebs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployweb-viewer-role
rules:
- apiGroups:
  - web.czy.io
  resources:
  - deploywebs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - web.czy.io
  resources:
  - deploywebs/status
  verbs:
  - get
